import { useState } from 'react';

import Head from 'next/head';
import Search from '../components/Search/Search';
import Content from '../components/Search/Content/Content';
import axios from 'axios';

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [playerProfile, setPlayerProfile] = useState(null);
  const [eachMatchData, setEachMatchData] = useState(null);

  const fetchPlayerData = async (enteredUsername) => {
    setErrorMsg('');
    setLoading(true);
    try {
      const response = await axios.get(
        `/api/getData?username=${enteredUsername}`
      );
      //Set states
      setPlayerProfile((prevState) => ({
        ...prevState,
        profileIconId: response.data.profileIconId,
        profileLevel: response.data.profileLevel,
        name: response.data.username,
      }));
      setEachMatchData(response.data.matchData);
      setLoading(false);
    } catch (error) {
      setErrorMsg('Username does not exist');
    }
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Search onSearchUsername={fetchPlayerData} />
      <Content
        loading={loading}
        errorMsg={errorMsg}
        playerProfile={playerProfile}
        eachMatchData={eachMatchData}
      />
    </>
  );
}
